import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Image Optimiser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
